# mappings.py

# Mapping subtopics to course IDs
SUBTOPIC_TO_COURSE = {
    "Mechanics": [3, 11],  # 11th Grade Physics: Mechanics & Thermodynamics, Rotational Dynamics
    "Magnetism": [4, 8],   # 12th Grade Physics: Electromagnetism & Modern Physics, Waves & Optics
    "Modern Physics": [4],
    "Gravitation": [3],
    "Thermodynamics": [3],
    "Electricity": [4],
    "Optics": [8],
    "Organic Chemistry": [5, 12],
    "Physical Chemistry": [6],
    "Periodic Table": [9],
    "Vectors": [10],
    "Trigonometry": [7],
}

# Full course details
COURSES = [
    {
        "id": 1,
        "title": "11th Grade Mathematics: Algebra & Calculus Foundations",
        "description": "Master key mathematical concepts for 11th grade including functions, limits, and introduction to calculus with practice problems and step-by-step solutions.",
        "thumbnail": "https://placehold.co/600x400/indigo/white?text=Math+11",
        "category": "Mathematics",
        "level": "Intermediate",
        "rating": 4.8,
        "reviewsCount": 312,
        "studentsCount": 14560,
        "isFree": True,
        "duration": "8h 45m",
        "instructor": "Dr. Jane Smith",
        "grade": "11th"
    },
    {
        "id": 2,
        "title": "12th Grade Mathematics: Advanced Calculus & Statistics",
        "description": "Complete preparation for 12th grade mathematics exams with advanced calculus, probability, and statistics modules designed for college readiness.",
        "thumbnail": "https://placehold.co/600x400/indigo/white?text=Math+12",
        "category": "Mathematics",
        "level": "Advanced",
        "rating": 4.9,
        "reviewsCount": 245,
        "studentsCount": 12780,
        "isFree": True,
        "duration": "10h 30m",
        "instructor": "Prof. David Wilson",
        "grade": "12th"
    },
    {
        "id": 3,
        "title": "11th Grade Physics: Mechanics & Thermodynamics",
        "description": "Build a strong foundation in physics principles with practical examples, interactive simulations, and problem-solving techniques focused on mechanics and thermodynamics.",
        "thumbnail": "https://placehold.co/600x400/orange/white?text=Physics+11",
        "category": "Physics",
        "level": "Intermediate",
        "rating": 4.7,
        "reviewsCount": 187,
        "studentsCount": 9753,
        "isFree": True,
        "duration": "9h 15m",
        "instructor": "Prof. Robert Johnson",
        "grade": "11th"
    },
    {
        "id": 4,
        "title": "12th Grade Physics: Electromagnetism & Modern Physics",
        "description": "Master electricity, magnetism, optics, and modern physics concepts with experimental demonstrations and exam preparation strategies.",
        "thumbnail": "https://placehold.co/600x400/orange/white?text=Physics+12",
        "category": "Physics",
        "level": "Advanced",
        "rating": 4.6,
        "reviewsCount": 203,
        "studentsCount": 8945,
        "isFree": True,
        "duration": "11h 20m",
        "instructor": "Dr. Alan Richards",
        "grade": "12th"
    },
    {
        "id": 5,
        "title": "11th Grade Chemistry: Organic Chemistry Fundamentals",
        "description": "Explore the fascinating world of organic chemistry, chemical bonding, and stoichiometry with interactive molecular visualizations and practice problems.",
        "thumbnail": "https://placehold.co/600x400/green/white?text=Chemistry+11",
        "category": "Chemistry",
        "level": "Intermediate",
        "rating": 4.8,
        "reviewsCount": 156,
        "studentsCount": 7421,
        "isFree": True,
        "duration": "7h 30m",
        "instructor": "Dr. Emily Chang",
        "grade": "11th"
    },
    {
        "id": 6,
        "title": "12th Grade Chemistry: Physical Chemistry & Equilibrium",
        "description": "Master advanced chemistry concepts including chemical equilibrium, thermodynamics, and electrochemistry with real-world applications and exam preparation.",
        "thumbnail": "https://placehold.co/600x400/green/white?text=Chemistry+12",
        "category": "Chemistry",
        "level": "Advanced",
        "rating": 4.7,
        "reviewsCount": 189,
        "studentsCount": 6890,
        "isFree": True,
        "duration": "9h 45m",
        "instructor": "Prof. Sarah Williams",
        "grade": "12th"
    },
    {
        "id": 7,
        "title": "Mathematics: Trigonometry & Coordinate Geometry for 11th Grade",
        "description": "Comprehensive coverage of trigonometric functions, identities, and coordinate geometry with visualization tools and exam-focused problem sets.",
        "thumbnail": "https://placehold.co/600x400/indigo/white?text=Trigonometry",
        "category": "Mathematics",
        "level": "Intermediate",
        "rating": 4.5,
        "reviewsCount": 178,
        "studentsCount": 8120,
        "isFree": True,
        "duration": "6h 50m",
        "instructor": "Dr. Kevin Matthews",
        "grade": "11th"
    },
    {
        "id": 8,
        "title": "Physics: Waves & Optics for 12th Grade",
        "description": "Detailed exploration of wave phenomena, sound, light, and optical instruments with interactive simulations and problem-solving strategies.",
        "thumbnail": "https://placehold.co/600x400/orange/white?text=Optics",
        "category": "Physics",
        "level": "Advanced",
        "rating": 4.8,
        "reviewsCount": 167,
        "studentsCount": 5923,
        "isFree": True,
        "duration": "7h 15m",
        "instructor": "Dr. Michelle Parker",
        "grade": "12th"
    },
    {
        "id": 9,
        "title": "Chemistry: Periodic Table & Chemical Bonds for 11th Grade",
        "description": "Deep dive into the periodic table trends, chemical bonding theories, and molecular structures with 3D visualizations and practice assessments.",
        "thumbnail": "https://placehold.co/600x400/green/white?text=Periodic+Table",
        "category": "Chemistry",
        "level": "Intermediate",
        "rating": 4.6,
        "reviewsCount": 142,
        "studentsCount": 6245,
        "isFree": True,
        "duration": "8h 10m",
        "instructor": "Prof. Thomas Lee",
        "grade": "11th"
    },
    {
        "id": 10,
        "title": "Mathematics: Vectors & 3D Geometry for 12th Grade",
        "description": "Master vector algebra, 3D coordinate systems, and spatial geometry with interactive tools and exam-focused problem solving techniques.",
        "thumbnail": "https://placehold.co/600x400/indigo/white?text=Vectors",
        "category": "Mathematics",
        "level": "Advanced",
        "rating": 4.7,
        "reviewsCount": 198,
        "studentsCount": 7645,
        "isFree": True,
        "duration": "9h 20m",
        "instructor": "Dr. Rachel Cohen",
        "grade": "12th"
    },
    {
        "id": 11,
        "title": "Physics: Rotational Dynamics for 11th Grade",
        "description": "Comprehensive coverage of rotational motion, torque, angular momentum, and moment of inertia with practical demonstrations and solved examples.",
        "thumbnail": "https://placehold.co/600x400/orange/white?text=Rotation",
        "category": "Physics",
        "level": "Intermediate",
        "rating": 4.5,
        "reviewsCount": 132,
        "studentsCount": 5842,
        "isFree": True,
        "duration": "6h 40m",
        "instructor": "Prof. James Wilson",
        "grade": "11th"
    },
    {
        "id": 12,
        "title": "Chemistry: Organic Reactions & Mechanisms for 12th Grade",
        "description": "Detailed exploration of organic reaction mechanisms, functional groups, and synthesis strategies with practice problems and visualization tools.",
        "thumbnail": "https://placehold.co/600x400/green/white?text=Organic",
        "category": "Chemistry",
        "level": "Advanced",
        "rating": 4.8,
        "reviewsCount": 157,
        "studentsCount": 6130,
        "isFree": True,
        "duration": "10h 15m",
        "instructor": "Dr. Olivia Martinez",
        "grade": "12th"
    }
]
